<?php if(!defined("__XE__")) exit();
$db_info = (object)array (
  'master_db' => 
  array (
    'db_type' => 'mysqli_innodb',
    'db_port' => '3306',
    'db_hostname' => 'localhost',
    'db_userid' => 'heakangc',
    'db_password' => 'heakang691*',
    'db_database' => 'heakangc',
    'db_table_prefix' => 'xe_',
  ),
  'slave_db' => 
  array (
    0 => 
    array (
      'db_type' => 'mysqli_innodb',
      'db_port' => '3306',
      'db_hostname' => 'localhost',
      'db_userid' => 'heakangc',
      'db_password' => 'heakang691*',
      'db_database' => 'heakangc',
      'db_table_prefix' => 'xe_',
    ),
  ),
  'default_url' => 'http://localhost/',
  'use_mobile_view' => 'N',
  'use_rewrite' => 'Y',
  'time_zone' => '+0900',
  'use_prepared_statements' => 'Y',
  'qmail_compatibility' => 'N',
  'use_db_session' => 'N',
  'use_ssl' => 'none',
  'sitelock_whitelist' => 
  array (
    0 => '127.0.0.1',
  ),
  'embed_white_object' => 
  array (
    0 => 'http://api.v.daum.net/',
    1 => 'http://blogdoc.nate.com/flash/blogdoc_widget_reco.swf',
    2 => 'http://dbi.video.cyworld.com/v.sk/',
    3 => 'http://doc.mgoon.com/player/',
    4 => 'http://event.dn.naver.com/sbsplayer/vmplayer.xap',
    5 => 'http://flvr.pandora.tv/flv2pan/',
    6 => 'http://flvs.daum.net/flvPlayer.swf',
    7 => 'http://imgcdn.pandora.tv/gplayer/flJal.swf',
    8 => 'http://imgcdn.pandora.tv/gplayer/pandora_EGplayer.swf',
    9 => 'http://musicplayer.naver.com/naverPlayer/posting/',
    10 => 'http://netv.sbs.co.kr/sbox/',
    11 => 'http://news.sbs.co.kr/',
    12 => 'http://onemore.imbc.com/ClientBin/oneplus.xap',
    13 => 'http://play.mgoon.com/',
    14 => 'http://play.tagstory.com/player/',
    15 => 'http://player.music.naver.com/naverPlayer/posting/',
    16 => 'http://sbsplayer.sbs.co.kr/',
    17 => 'http://scrap.ad.naver.com/',
    18 => 'http://serviceapi.nmv.naver.com/',
    19 => 'http://static.campaign.naver.com/',
    20 => 'http://tvpot.daum.net/playlist/playlist.swf',
    21 => 'http://v.egloos.com/v.sk/',
    22 => 'http://v.nate.com/v.sk/',
    23 => 'http://videofarm.daum.net/',
    24 => 'http://vmark.kbs.co.kr/zzim/vmplayer/vmplayer.xap',
    25 => 'http://w.blogdoc.nate.com/',
    26 => 'http://wizard2.sbs.co.kr/',
    27 => 'http://www.kbs.co.kr/zzim/vmplayer/vmplayer.xap',
    28 => 'http://www.tagstory.com/player/basic/',
    29 => 'http://www.youtube-nocookie.com/',
    30 => 'http://www.youtube.com/',
    31 => 'https://www.youtube-nocookie.com/',
    32 => 'https://www.youtube.com/',
  ),
  'embed_white_iframe' => 
  array (
    0 => 'http://flvs.daum.net/',
    1 => 'http://maps.google.co.kr/',
    2 => 'http://maps.google.com/',
    3 => 'http://player.vimeo.com/',
    4 => 'http://sbsplayer.sbs.co.kr/',
    5 => 'http://serviceapi.rmcnmv.naver.com/',
    6 => 'http://www.youtube-nocookie.com/',
    7 => 'http://www.youtube.com/',
    8 => 'https://www.youtube-nocookie.com/',
    9 => 'https://www.youtube.com/',
  ),
);